---
title: "Some proofs from discrete mathematics"
author: "John Blischak"
date: "2019-01-25"
output: workflowr::wflow_html
---

## Even and odd integers

> If $k$ is any odd integer and $m$ is any even integer, then $k^{2} + m^{2}$ is
odd.

**Proof:** Let $k$ and $m$ be any integers, and suppose that $k$ is odd and $m$
is even. By definition of odd, $k = 2r + 1$ for some integer $r$. By definition
of even, $m = 2s$ for some integer $s$. It follows that

$$ k^{2} + m^{2} = (2r + 1)^{2} + (2s)^{2} $$

$$ = 2(2r^{2} + 2r + 2s^{2}) + 1. $$

$2r^{2} + 2r + 2s^{2}$ is an integer because sums and products of integers are
integers. By definition of odd, $k^{2} + m^{2}$ is odd. $\square$

## Divisibility

> For all integers $a$, $b$, and $c$, if $a|b$ and $a|c$ then $a|(2b - 3c)$.

**Proof:** Let $a$, $b$, and $c$ be any integers and suppose $a|b$ and $a|c$. By
definition of divisibilty, $b = ra$ and $c = sa$ for some integers $r$ and $s$.
It follows that

$$ 2b - 3c = 2(ra) - 3(sa) = a(2r - 3s).  $$

$2r - 3s$ is an integer because sums and products of integers are integers. Thus
by definition of divisibility, $a|(2b - 3c)$. $\square$

## Quotient-Remainder Theorem

> The square of any integer has the form $3k$ or $3k + 1$ for some integer $k$.

**Proof:** Let $n$ be any integer, then by QRT (with $d = 3$) $n = 3q + r$ for
some integers $q$ and $r$ with $0 \leq r < 3$.

* *Case 1:* Suppose $r = 0$. Then $n = 3q + 0 = 3q$ and $n^{2} = (3q)^{2} =
3(3q^{2})$. Let $k = 3q^{2}$, which is an integer because products of integers
are integers. Thus $n^{2} = 3k$.

* *Case 2:* Suppose $r = 1$. Then $n = 3q + 1$ and $n^{2} = (3q + 1)^{2} =
3(3q^{2} + 2q) + 1$. Let $k = 3q^{2} + 2q$, which is an integer because sums and
products of integers are integers. Thus $n^{2} = 3k + 1$.

* *Case 3:* Suppose $r = 2$. Then $n = 3q + 2$ and $n^{2} = (3q + 2)^{2} =
3(3q^{2} + 4q + 1) + 1$. Let $k = 3q^{2} + 4q + 1$, which is an integer because
sums and products of integers are integers. Thus $n^{2} = 3k + 1$.

Therefore, in all cases $n^{2} = 3k$ or $n^{2} = 3k + 1$. $\square$

## Logarithms

The following proof is from *Discrete Mathemtics with Applications, 4th Edition*
by Susanna S. Epp (p. 407).

> For any positive real numbers $b$, $c$, and $x$, with $b \neq 1$ and $c \neq 1$,
>
> $$ log_{c}x = \frac{log_{b}x}{log_{b}c}.$$

**Proof:** Suppose positive real numbers $b$, $c$, and $x$, with $b \neq 1$ and
$c \neq 1$. Let

$$
\begin{align*}
  u = log_{b}c \>\>\>\> (1) \\
  v = log_{c}x \>\>\>\> (2) \\
  w = log_{b}x \>\>\>\> (3)
\end{align*}
$$

Then, by definition of logarithm,

$$
\begin{align*}
  c = b^u \>\>\>\> (1') \\
  x = c^v \>\>\>\> (2') \\
  x = b^w \>\>\>\> (3')
\end{align*}
$$
Substituting (1') into (2') and using one of the laws of exponents,
$(b^{u})^v = b^{uv}$, gives

$$ x = c^v = (b^u)^v = b^{uv} $$

But by (3'), $x = b^w$ also. Hence

$$ b^{uv} = b^{w}, $$

and so by the one-to-oneness of the exponential function
(if $b^u = b^v$ then $u = v$),

$$ uv = w. $$

Substituting from (1), (2), and (3) gives that

$$ (log_{b}c)(log_{c}x) = log_{b}x. $$

And dividing both sides by $log_{b}c$ (which is nonzero because $c \neq 1$)
results in

$$ log_{c}x = \frac{log_{b}x}{log_{b}c}. \>\>\>\>  \square$$
